[[themes]]
name = "rose-pine-no-bg"
[themes.palette]
black = "#26233A"
red = "#EB6F92"
green = "#31748F"
yellow = "#F6C177"
blue = "#9CCFD8"
magenta = "#C4A7E7"
cyan = "#EBBCBA"
white = "#E0DEF4"
bright_black = "#6E6A86"
bright_red = "#EB6F92"
bright_green = "#31748F"
bright_yellow = "#F6C177"
bright_blue = "#9CCFD8"
bright_magenta = "#C4A7E7"
bright_cyan = "#EBBCBA"
bright_white = "#E0DEF4"
